# 1. Use the modern, supported Eclipse Temurin Java 17 base image
FROM eclipse-temurin:17-jre

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy the compiled JAR file generated by your Maven build stage
COPY target/*.jar app.jar

# 4. Expose the port your Spring Boot app runs on
EXPOSE 8080

# 5. Command to run the Java app when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
